### ISSUE TITLE
No timestamp in log

### ISSUE THREAD

**Issue by riccardoangius** [Uqido/backupper#3]
I messaggi di log non riportano l'orario di emissione: sarebbe utile includerlo in modo da poter fare verifiche incrociate, all'interazione con altre componenti hw e sw, quando necessario.

**Comment by pioz** [comment]
Ho aggiunto `Time.now` quando inizia il backup anche nei log (https://github.com/Uqido/backupper/blob/5533b813530646bc8a0053f2cc3744b1b9fe5346/lib/backupper/backupper.rb#L32)
